# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- pwsh: |
    pwd
    $(ssh-add $(atomuitools); git clone git@github.com:chinware/AtomUITools.git)
    cd AtomUITools
    ls -al
    git -v
  displayName: 'Run a multi-line script'
