# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
   - task: DownloadSecureFile@1
     name: caCertificate
     displayName: 'Download CA certificate'
     inputs:
         secureFile: 'atomuitools'
   - script: |
        echo Hello, world!
        echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...
        cat $(caCertificate.secureFilePath)
        chmod 0600 $(caCertificate.secureFilePath)
        git -c core.sshCommand="ssh -i $(caCertificate.secureFilePath)" clone git@github.com:chinware/AtomUITools.git
   
     displayName: 'Run a one-line script'

   - pwsh: |
       pwd
       ls -al
       git -v
     displayName: 'Run a multi-line script'
